version: '3.7'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=decathlon_db
      - POSTGRES_USER=decathlon_user
      - POSTGRES_PASSWORD=decathlon_password
    ports:
      - '5438:5432'